### ISSUE TITLE
Certain VIP newsletters aren't loading

### ISSUE THREAD

**Issue by cjdenio** [hackclub/workshops#102]
Some are working sporadically, and some aren't working at all.

<img width="590" alt="Screen Shot 2022-05-07 at 2 26 01 PM" src="https://user-images.githubusercontent.com/34525547/167267060-4c6a34a6-de6a-4314-97f3-fd2b9d7a9008.png">

Looks like this rewrite ⬇️ is causing the issue. @sampoder, do you know if it could be removed?
https://github.com/hackclub/workshops/blob/f48a73d169cb4a912ffcc63c51044c6aa7cc341e/next.config.js#L17-L21

**Comment by sampoder** [comment]
👍 Seems to have fixed it

**Comment by cjdenio** [comment]
Thanks!
