### ISSUE TITLE
bug: Thunderstorm image doesn't render

### ISSUE THREAD

**Issue by LucasHT22** [hackclub/workshops#107]
![image](https://user-images.githubusercontent.com/88567622/197610230-e928acf8-a3f0-493c-9a29-c7b171d16471.png)

**Comment by jaspermayone** [comment]
Cannot repro
![CleanShot 2024-03-29 at 19 54 57@2x](https://github.com/hackclub/workshops/assets/65788728/057dd17a-4cf2-4c69-90e4-25fdbd333fbc)

**Comment by LucasHT22** [comment]
I think it was already fixed! Tks anyway:)
