### ISSUE TITLE
Add a Sprig section

### ISSUE THREAD

**Issue by karamassie** [hackclub/workshops#108]
As we are developing more workshops for Sprig, it'd be great to have a section. The text could read "guides to make games using our online editor. Submitted games can win a gaming device." (or something like this). with a link to the sprig homepage!

**Comment by SamDev-7** [comment]
Should be possible by editing [`manifest.json`](https://github.com/hackclub/workshops/blob/main/manifest.json).
I'll happily make a PR if wanted.

**Comment by karamassie** [comment]
yes pls!

**Comment by exu3** [comment]
Closed by #109
