### ISSUE TITLE
Use fallback/regeneration for workshop pages

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/workshops#47]
It’d be great to use `fallback: true` & `revalidate` so workshop pages would automatically refresh themselves off GitHub (hackclub/hackclub) instead of rebuilding the entire site on every commit of that repo. (That’s currently happening via a GitHub webhook hitting Vercel, which any HQ member can disable if it’s no longer needed.)

(Bonus: add regeneration to the Conduct page & fallback to VIP Newsletters as well!)

I’m not planning to take this on, but please go for it if you’re feeling inspired! Happy to help.

**Comment by sampoder** [comment]
Closed in #66!

**Comment by sampoder** [comment]
Reopening because the downloading broke

**Comment by akeem406** [comment]
Good morning from here please I need help on to hack social media

**Comment by sampoder** [comment]
🎉  Finally, this has been completed! And is working!
